'use client';
import {useEffect,useRef,useState} from 'react';
import {io} from 'socket.io-client';
const socket=io(process.env.NEXT_PUBLIC_SOCKET_URL||'http://localhost:3001',{autoConnect:false});
type Character={id:string;name:string;hp:number;kingdomTh?:string;skills:{name:string;description:string}[]};
type Card={id:string;name:string;suit:string;number:string;effect:string|null};
type Player={id:string;username:string;ready:boolean;confirmedCharacter:boolean;alive:boolean;handCount:number;hand:Card[];character?:Character;characterOptions:Character[];hp?:number;maxHp?:number};
type RoleSet={emperor:number;loyalist:number;rebel:number;traitor:number};
type Game={viewerId:string;hostId:string;phase:string;currentPlayerId?:string;lastPlayedCard?:Card;pendingAction?:{kind:'attack';actorId:string;targetId:string};players:Player[];deck:{length:number};discard:{length:number};log:{message:string}[]};
const roleText=(role:RoleSet)=>`จักรพรรดิ ${role.emperor} · ผู้ภักดี ${role.loyalist} · กบฏ ${role.rebel} · คนทรยศ ${role.traitor}`;
const seatStyle=(index:number,total:number)=>{const radians=(-90+(360/total)*index)*Math.PI/180;return {left:`${50+44*Math.cos(radians)}%`,top:`${50+46*Math.sin(radians)}%`}};
export default function Home(){
 const [game,setGame]=useState<Game|undefined>(undefined),[room,setRoom]=useState('demo'),[name,setName]=useState(''),[text,setText]=useState(''),[chat,setChat]=useState<{username:string;text:string}[]>([]),[roleOptions,setRoleOptions]=useState<RoleSet[]>([]),[selectedCard,setSelectedCard]=useState<Card|undefined>(undefined),[soundOn,setSoundOn]=useState(true);const lastTurn=useRef<string|undefined>(undefined);
 useEffect(()=>{const state=(value:Game)=>setGame(value),message=(value:{username:string;text:string})=>setChat(items=>[...items,value]),options=(value:RoleSet[])=>setRoleOptions(value),error=(value:string)=>alert(value);socket.on('game:state',state);socket.on('chat:message',message);socket.on('game:role-options',options);socket.on('game:error',error);return()=>{socket.off('game:state',state);socket.off('chat:message',message);socket.off('game:role-options',options);socket.off('game:error',error)}},[]);
 const join=()=>{socket.connect();socket.emit('room:join',{gameId:room,username:name})};
 useEffect(()=>{const turn=game?.currentPlayerId;if(soundOn&&turn&&turn===game.viewerId&&lastTurn.current!==turn){const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(660,context.currentTime);oscillator.frequency.exponentialRampToValueAtTime(880,context.currentTime+.16);gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.12,context.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.24);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.25)}lastTurn.current=turn},[game?.currentPlayerId,game?.viewerId,soundOn]);
 if(!game)return <main className="lobby"><h1 className="game-title">ยุทธพิชัยสามก๊ก</h1><p>เข้าสู่สมรภูมิและรวมพลสหายของคุณ</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Username"/><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Room ID"/><button onClick={join}>เข้าห้อง</button></main>;
 const isHost=game.hostId===game.viewerId,waiting=game.phase==='waiting',chooser=game.players.find(player=>!player.confirmedCharacter&&player.characterOptions.length>0),isMyTurn=game.currentPlayerId===game.viewerId,myPlayer=game.players.find(player=>player.id===game.viewerId);
 return <main><header><h1 className="game-title">ยุทธพิชัยสามก๊ก</h1><span className="phase">{game.phase}</span></header>
  <section className="table-scene"><div className="table"><div className="center">{waiting?<div className="waiting-actions"><b>ห้องกำลังรอผู้เล่น</b><button onClick={()=>socket.emit('player:ready',{gameId:room,ready:!myPlayer?.ready})}>{myPlayer?.ready?'Unready':'Ready'}</button>{isHost?<button onClick={()=>socket.emit('game:start',{gameId:room})}>♛ เริ่มเกม</button>:<small>รอหัวหน้าห้องเริ่มเกม</small>}</div>:<>กองจั่ว <strong>{game.deck.length}</strong><br/>กองทิ้ง <strong>{game.discard.length}</strong>{game.lastPlayedCard&&<div className="last-card"><small>ไพ่ล่าสุด</small><b>{game.lastPlayedCard.name}</b><span>{game.lastPlayedCard.number} {game.lastPlayedCard.suit}</span></div>}</>}</div></div><div className="seats">{game.players.map((player,index)=>{const canTarget=Boolean(selectedCard&&isMyTurn&&player.alive&&(selectedCard.effect!=='attack'||player.id!==game.viewerId));return <article key={player.id} onClick={()=>{if(canTarget){socket.emit('card:play',{gameId:room,cardId:selectedCard!.id,targetId:player.id});setSelectedCard(undefined)}}} className={`player-seat ${player.id===game.currentPlayerId?'active-player':''} ${canTarget?'targetable':''}`} style={seatStyle(index,game.players.length)}><b>{player.id===game.hostId&&<span className="crown" title="หัวหน้าห้อง">♛</span>}{player.username}</b><span className="avatar">{player.username.slice(0,1).toUpperCase()}</span>{player.character?<><p className="general-name">{player.character.name}</p><p className="hp">HP {player.hp}/{player.maxHp}</p></>:waiting?<p className={`ready-status ${player.ready?'ready':'not-ready'}`}>{player.ready?'พร้อม':'ไม่พร้อม'}</p>:null}</article>})}</div></section>
  {roleOptions.length>0&&isHost&&<section className="choice"><h2>เลือกชุดบทบาท</h2>{roleOptions.map((role,index)=><button key={index} onClick={()=>{socket.emit('game:start',{gameId:room,composition:role});setRoleOptions([])}}>{roleText(role)}</button>)}</section>}
  {game.phase==='character-select'&&chooser&&<section className="choice"><h2>เลือกขุนพลของคุณ</h2><div className="character-grid">{chooser.characterOptions.map(character=><article key={character.id}><h3 className="general-name">{character.name}</h3><p>{character.kingdomTh||'—'} · HP {character.hp}</p>{character.skills.map(skill=><p key={skill.name}><b>{skill.name}</b> — {skill.description}</p>)}<button onClick={()=>socket.emit('character:select',{gameId:room,characterId:character.id})}>เลือก {character.name}</button></article>)}</div></section>}
  {game.phase==='playing'&&<section className="hand"><h2>ไพ่ของคุณ {isMyTurn&&<span className="your-turn">— เป็นตาของคุณ!</span>}</h2>{selectedCard&&<p className="target-hint">เลือกเป้าหมายของ “{selectedCard.name}” โดยคลิกผู้เล่นบนโต๊ะ <button onClick={()=>setSelectedCard(undefined)}>ยกเลิก</button></p>}{myPlayer?.hand.map(card=><button disabled={!isMyTurn} className={selectedCard?.id===card.id?'selected-card':''} key={card.id} onClick={()=>{if(card.effect==='attack'||card.effect==='heal')setSelectedCard(card);else socket.emit('card:play',{gameId:room,cardId:card.id})}}>{card.name} {card.number} {card.suit}</button>)}{isMyTurn&&<button onClick={()=>socket.emit('turn:end',{gameId:room})}>จบเทิร์น</button>}{game.pendingAction?.targetId===game.viewerId&&<section className="choice"><h2>ถูกโจมตี — ตอบสนอง</h2>{myPlayer?.hand.filter(card=>card.effect==='dodge').map(card=><button key={card.id} onClick={()=>socket.emit('attack:respond',{gameId:room,cardId:card.id})}>ใช้หลบ</button>)}<button className="danger" onClick={()=>socket.emit('attack:respond',{gameId:room})}>ไม่หลบ (รับความเสียหาย)</button></section>}</section>}
  <section className="support-grid"><section className="game-log"><h2>บันทึกการศึก</h2><div>{game.log.length?[...game.log].reverse().slice(0,20).map((entry,index)=><p key={index}>{entry.message}</p>):<p>ยังไม่มีเหตุการณ์</p>}</div></section><section className="chat"><h2>Chat</h2><div>{chat.map((message,index)=><p key={index}><b>{message.username}</b>: {message.text}</p>)}</div><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&text.trim()){socket.emit('chat:send',{gameId:room,text});setText('')}}} placeholder="พิมพ์ข้อความ"/></section></section>
 <button className="sound-toggle" title="เปิด/ปิดเสียงแจ้งเตือน" onClick={()=>setSoundOn(value=>!value)}>{soundOn?'🔔':'🔕'}</button></main>;
}
