'use client';
import {useEffect,useRef,useState} from 'react';
import {io} from 'socket.io-client';
import { LobbyTable } from '../components/LobbyTable';
const socket=io(process.env.NEXT_PUBLIC_SOCKET_URL||'http://localhost:3001',{autoConnect:false});
type Role='emperor'|'loyalist'|'rebel'|'traitor';
type RoleDefinition={role_key:Role;role_th:string;visibility:string;win_condition_th:string;team:string};
type Character={id:string;name:string;hp:number;kingdomTh?:string;skills:{name:string;description:string;condition?:string|null}[]};
type Card={id:string;name:string;type:string;suit:string;number:string;description:string|null;effect:string|null;conditions?:{timing?:string;targetRule?:string}};
type Member={id:string;username:string;connectionStatus:'online'|'disconnected';joinedAt:string;lastSeenAt:string};
type Player=Member&{seatIndex:number;role?:Role;ready:boolean;confirmedCharacter:boolean;alive:boolean;handCount:number;hand:Card[];character?:Character;characterOptions:Character[];hp?:number;maxHp?:number};
type RoleSet={emperor:number;loyalist:number;rebel:number;traitor:number};
type Game={viewerId:string;hostId:string;isSpectator:boolean;phase:string;currentPlayerId?:string;hasDrawnThisTurn:boolean;lastPlayedCard?:Card;pendingAction?:{kind:'attack';actorId:string;targetId:string};players:Player[];spectators:Member[];roleDefinitions?:RoleDefinition[];deck:{length:number};discard:{length:number};log:{message:string;at:string}[]};
type Room={id:string;playerCount:number;spectatorCount:number;host:string;status:string;hasPassword:boolean};
const roleText=(role:RoleSet)=>`จักรพรรดิ ${role.emperor} · ผู้ภักดี ${role.loyalist} · กบฏ ${role.rebel} · คนทรยศ ${role.traitor}`;
const roleLabel:Record<Role,string>={emperor:'จักรพรรดิ',loyalist:'ผู้ภักดี',rebel:'กบฏ',traitor:'คนทรยศ'};
const cardBack='🂠',drawPileLabel='กองจั่ว',discardPileLabel='กองทิ้ง',drawTurnLabel='จั่วไพ่ 2 ใบ';
const hearts=(hp?:number,maxHp?:number)=>hp===undefined||maxHp===undefined?null:<span className="hearts">{'♥'.repeat(Math.max(0,hp))}{'♡'.repeat(Math.max(0,maxHp-hp))}</span>;
export default function Home(){
 const [game,setGame]=useState<Game|undefined>(undefined),[room,setRoom]=useState('demo'),[name,setName]=useState(''),[userId,setUserId]=useState(''),[joinedRoom,setJoinedRoom]=useState(''),[text,setText]=useState(''),[chat,setChat]=useState<{username:string;text:string}[]>([]),[roleOptions,setRoleOptions]=useState<RoleSet[]>([]),[selectedCard,setSelectedCard]=useState<Card|undefined>(undefined),[detailCard,setDetailCard]=useState<Card|undefined>(undefined),[detailCharacter,setDetailCharacter]=useState<Character|undefined>(undefined),[showRole,setShowRole]=useState(false),[discardMode,setDiscardMode]=useState(false),[discardIds,setDiscardIds]=useState<string[]>([]),[confirmDiscard,setConfirmDiscard]=useState(false),[soundOn,setSoundOn]=useState(true),[rooms,setRooms]=useState<Room[]>([]);const lastTurn=useRef<string|undefined>(undefined),revealedRole=useRef<Role|undefined>(undefined);
 useEffect(()=>{let id=localStorage.getItem('wtk-member-id');if(!id){id=crypto.randomUUID();localStorage.setItem('wtk-member-id',id)}setUserId(id)},[]);
 useEffect(()=>{const state=(value:Game)=>setGame(value),message=(value:{username:string;text:string})=>setChat(items=>[...items,value]),options=(value:RoleSet[])=>setRoleOptions(value),error=(value:string)=>alert(value);socket.on('game:state',state);socket.on('chat:message',message);socket.on('game:role-options',options);socket.on('game:error',error);return()=>{socket.off('game:state',state);socket.off('chat:message',message);socket.off('game:role-options',options);socket.off('game:error',error)}},[]);
 useEffect(()=>{const reconnect=()=>{if(joinedRoom&&userId)socket.emit('room:join',{gameId:joinedRoom,username:name,userId})};socket.on('connect',reconnect);return()=>{socket.off('connect',reconnect)}},[joinedRoom,userId,name]);
 const loadRooms=()=>fetch(process.env.NEXT_PUBLIC_SERVER_URL||'http://localhost:3001/rooms').then(response=>response.json()).then(setRooms).catch(()=>setRooms([]));
 useEffect(()=>{loadRooms()},[]);
 const join=(roomId=room)=>{if(!userId)return;socket.connect();setJoinedRoom(roomId);socket.emit('room:join',{gameId:roomId,username:name,userId})};
 useEffect(()=>{const turn=game?.currentPlayerId;if(soundOn&&turn&&turn===game.viewerId&&lastTurn.current!==turn){const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(660,context.currentTime);oscillator.frequency.exponentialRampToValueAtTime(880,context.currentTime+.16);gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.12,context.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.24);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.25)}lastTurn.current=turn},[game?.currentPlayerId,game?.viewerId,soundOn]);
 useEffect(()=>{const role=game?.players.find(player=>player.id===game.viewerId)?.role;if(role&&revealedRole.current!==role){revealedRole.current=role;setShowRole(true)}},[game?.players,game?.viewerId]);
 if(!game)return <main className="lobby"><h1 className="game-title">ยุทธพิชัยสามก๊ก</h1><p>เข้าสู่สมรภูมิและรวมพลสหายของคุณ</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Username"/><section className="room-browser"><div><h2>ห้องที่เปิดอยู่</h2><button onClick={loadRooms}>รีเฟรช</button></div>{rooms.length?rooms.map(item=><article key={item.id}><b>{item.id}</b><span>{item.status==='waiting'?'กำลังรอผู้เล่น':'กำลังเล่น — Spectator'}</span><small>หัวหน้าห้อง: {item.host} · ผู้เล่น {item.playerCount} · ผู้ชม {item.spectatorCount}</small><button disabled={!name||!userId} onClick={()=>join(item.id)}>{item.status==='waiting'?'เข้าห้อง':'เข้าชม'}</button></article>):<p>ยังไม่มีห้องที่เปิดอยู่</p>}</section><section className="create-room"><h2>สร้างห้องใหม่</h2><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="ชื่อห้อง"/><button disabled={!name||!userId} onClick={()=>join()}>สร้าง/เข้าห้อง</button></section></main>;
 const isHost=game.hostId===game.viewerId,waiting=game.phase==='waiting',chooser=game.players.find(player=>!player.confirmedCharacter&&player.characterOptions.length>0),isMyTurn=game.currentPlayerId===game.viewerId,myPlayer=game.players.find(player=>player.id===game.viewerId),myRoleInfo=game.roleDefinitions?.find(role=>role.role_key===myPlayer?.role),requiredDiscard=Math.max(0,(myPlayer?.hand.length||0)-(myPlayer?.hp||0)),pendingTarget=game.players.find(player=>player.id===game.pendingAction?.targetId),pendingActor=game.players.find(player=>player.id===game.pendingAction?.actorId),canPlay=isMyTurn&&game.hasDrawnThisTurn&&!game.pendingAction&&!discardMode,emperor=game.players.find(player=>player.role==='emperor'),waitingForCharacter=game.players.filter(player=>!player.confirmedCharacter),anchorSeat=myPlayer?.seatIndex||1;
 const handStatus=game.pendingAction?(game.pendingAction.targetId===game.viewerId?'— คุณถูกโจมตี: ตัดสินใจตอบโต้':game.pendingAction.actorId===game.viewerId?`— กำลังรอ ${pendingTarget?.username||'เป้าหมาย'} ตอบโต้`:`— กำลังรอ ${pendingTarget?.username||'ผู้เล่น'} ตอบโต้การโจมตีของ ${pendingActor?.username||'ผู้เล่น'}`):(isMyTurn?(game.hasDrawnThisTurn?'— เป็นตาของคุณ!':'— ถึงตาคุณแล้ว: กรุณาจั่วไพ่'):'');
 const renderLog=(message:string)=>{const names=game.players.map(player=>player.username).sort((a,b)=>b.length-a.length),escaped=names.map(value=>value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));if(!escaped.length)return message;return message.split(new RegExp(`(${escaped.join('|')})`,'g')).map((part,index)=>names.includes(part)?<b key={index}>{part}</b>:part)};
 return <main><header><h1 className="game-title">ยุทธพิชัยสามก๊ก</h1><span className="phase">{game.isSpectator?'Spectator · ':''}{game.phase}</span></header>{game.isSpectator&&<p className="spectator-banner">คุณกำลังรับชมเกมนี้ในฐานะ Spectator</p>}{myPlayer?.role&&<button className="role-button" onClick={()=>setShowRole(true)}>บทบาทของฉัน</button>}{game.phase==='character-select'&&<p className="selection-banner">{!emperor?.confirmedCharacter?'จักรพรรดิกำลังเลือกขุนพล':waitingForCharacter.length?`กำลังรอ ${waitingForCharacter.map(player=>player.username).join(', ')} เลือกขุนพล`:'ผู้เล่นทุกคนเลือกขุนพลแล้ว กำลังเริ่มเกม'}</p>}
  <LobbyTable waiting={waiting} players={game.players} spectators={game.spectators} anchorSeatIndex={anchorSeat} viewerId={game.viewerId} hostId={game.hostId} currentPlayerId={game.currentPlayerId} selectedEffect={selectedCard?.effect} deckCount={game.deck.length} discardCount={game.discard.length} lastCard={game.lastPlayedCard} canDraw={isMyTurn&&!game.hasDrawnThisTurn&&!game.pendingAction} onDraw={()=>socket.emit('turn:draw',{gameId:room})} onLastCardClick={()=>game.lastPlayedCard&&setDetailCard(game.lastPlayedCard)} onSelectSeat={seatIndex=>socket.emit('seat:select',{gameId:room,seatIndex})} onRandomSeat={()=>socket.emit('seat:random',{gameId:room})} onReady={()=>socket.emit('player:ready',{gameId:room,ready:!myPlayer?.ready})} onSpectate={()=>socket.emit('seat:spectate',{gameId:room})} onStart={()=>socket.emit('game:start',{gameId:room})} onLeave={()=>{socket.emit('room:leave',{gameId:room});setGame(undefined);setJoinedRoom('');loadRooms()}} onTarget={player=>{if(selectedCard){socket.emit('card:play',{gameId:room,cardId:selectedCard.id,targetId:player.id});setSelectedCard(undefined)}}} onCharacterDetails={player=>player.character&&setDetailCharacter(player.character)} />
  {roleOptions.length>0&&isHost&&<section className="choice"><h2>เลือกชุดบทบาท</h2>{roleOptions.map((role,index)=><button key={index} onClick={()=>{socket.emit('game:start',{gameId:room,composition:role});setRoleOptions([])}}>{roleText(role)}</button>)}</section>}
  {game.phase==='character-select'&&chooser&&<section className="choice"><h2>เลือกขุนพลของคุณ</h2><div className="character-grid">{chooser.characterOptions.map(character=><article key={character.id}><h3 className="general-name">{character.name}</h3><p>{character.kingdomTh||'—'} · HP {character.hp}</p>{character.skills.map(skill=><p key={skill.name}><b>{skill.name}</b> — {skill.description}</p>)}<button onClick={()=>socket.emit('character:select',{gameId:room,characterId:character.id})}>เลือก {character.name}</button></article>)}</div></section>}
  {game.phase==='playing'&&<section className="hand"><h2>ไพ่ของคุณ {handStatus&&<span className={game.pendingAction?'response-status':'your-turn'}>{handStatus}</span>}</h2>{selectedCard&&<p className="target-hint">เลือกเป้าหมายของ “{selectedCard.name}” โดยคลิกผู้เล่นบนโต๊ะ <button onClick={()=>setSelectedCard(undefined)}>ยกเลิก</button></p>}{discardMode&&<p className="target-hint">เลือกไพ่ที่จะทิ้งอีก {requiredDiscard-discardIds.length} ใบ</p>}{isMyTurn&&!game.hasDrawnThisTurn&&!game.pendingAction&&<button onClick={()=>socket.emit('turn:draw',{gameId:room})}>{drawTurnLabel}</button>}<div className="hand-cards">{myPlayer?.hand.map(card=><article className={`${selectedCard?.id===card.id?'selected-card':''} ${discardIds.includes(card.id)?'discard-selected':''}`} key={card.id} onClick={()=>{if(discardMode)setDiscardIds(ids=>ids.includes(card.id)?ids.filter(id=>id!==card.id):[...ids,card.id]);else setDetailCard(card)}}><span>{card.number} {card.suit}</span><b>{card.name}</b><button disabled={!canPlay} onClick={event=>{event.stopPropagation();if(card.effect==='attack'||card.effect==='heal')setSelectedCard(card);else socket.emit('card:play',{gameId:room,cardId:card.id})}}>เล่น</button></article>)}</div>{isMyTurn&&!game.pendingAction&&requiredDiscard>0&&!discardMode&&<button onClick={()=>setDiscardMode(true)}>เลือกไพ่ที่จะทิ้ง ({requiredDiscard})</button>}{discardMode&&<><button disabled={discardIds.length!==requiredDiscard} onClick={()=>setConfirmDiscard(true)}>ทิ้งไพ่ที่เลือก</button><button onClick={()=>{setDiscardMode(false);setDiscardIds([]);setConfirmDiscard(false)}}>ยกเลิก</button></>}{isMyTurn&&<button disabled={requiredDiscard>0||Boolean(game.pendingAction)||!game.hasDrawnThisTurn} onClick={()=>socket.emit('turn:end',{gameId:room})}>จบเทิร์น</button>}{confirmDiscard&&<section className="choice"><h2>ยืนยันการทิ้งไพ่</h2><p>คุณเลือกทิ้ง {discardIds.length} ใบ ต้องการยืนยันหรือไม่?</p><button className="danger" onClick={()=>{socket.emit('hand:discard',{gameId:room,cardIds:discardIds});setConfirmDiscard(false);setDiscardMode(false);setDiscardIds([])}}>ยืนยันการทิ้ง</button><button onClick={()=>setConfirmDiscard(false)}>กลับไปเลือก</button></section>}{game.pendingAction?.targetId===game.viewerId&&<section className="choice"><h2>ถูกโจมตี — ตอบสนอง</h2>{myPlayer?.hand.filter(card=>card.effect==='dodge').map(card=><button key={card.id} onClick={()=>socket.emit('attack:respond',{gameId:room,cardId:card.id})}>ใช้หลบ</button>)}<button className="danger" onClick={()=>socket.emit('attack:respond',{gameId:room})}>ไม่หลบ (รับความเสียหาย)</button></section>}</section>}
  <section className="support-grid"><section className="game-log"><h2>บันทึกการศึก</h2><div>{game.log.length?[...game.log].reverse().slice(0,20).map((entry,index)=><p key={index}><time>{new Date(entry.at).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</time>{renderLog(entry.message)}</p>):<p>ยังไม่มีเหตุการณ์</p>}</div></section><section className="chat"><h2>Chat</h2><div>{chat.map((message,index)=><p key={index}><b>{message.username}</b>: {message.text}</p>)}</div><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&text.trim()){socket.emit('chat:send',{gameId:room,text});setText('')}}} placeholder="พิมพ์ข้อความ"/></section></section>
 {showRole&&myPlayer?.role&&<div className="modal-backdrop" onClick={()=>setShowRole(false)}><section className="role-reveal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setShowRole(false)}>×</button><small>บทบาทของคุณ</small><h2>{myRoleInfo?.role_th||roleLabel[myPlayer.role]}</h2><p>{myRoleInfo?.win_condition_th||'กำลังโหลดคำอธิบายบทบาท'}</p></section></div>}{detailCard&&<div className="modal-backdrop" onClick={()=>setDetailCard(undefined)}><section className="card-detail" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setDetailCard(undefined)}>×</button><div className="card-placeholder">CARD IMAGE<br/>PLACEHOLDER</div><span className="card-rank">{detailCard.number} {detailCard.suit}</span><h2>{detailCard.name}</h2><p><b>ประเภท:</b> {detailCard.type}</p><p>{detailCard.description||'ยังไม่มีคำอธิบาย'}</p></section></div>}{detailCharacter&&<div className="modal-backdrop" onClick={()=>setDetailCharacter(undefined)}><section className="card-detail character-detail" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setDetailCharacter(undefined)}>×</button><div className="card-placeholder">CHARACTER IMAGE<br/>PLACEHOLDER</div><h2>{detailCharacter.name}</h2><p><b>ก๊ก:</b> {detailCharacter.kingdomTh||'—'}</p>{detailCharacter.skills.map(skill=><article key={skill.name}><h3>{skill.name}</h3><p>{skill.description}</p>{skill.condition&&<details><summary>เงื่อนไขการใช้</summary><p>{skill.condition}</p></details>}</article>)}</section></div>}<button className="sound-toggle" title="เปิด/ปิดเสียงแจ้งเตือน" onClick={()=>setSoundOn(value=>!value)}>{soundOn?'🔔':'🔕'}</button></main>;
}
