'use client';

import { useState, type CSSProperties } from 'react';
import { canPlayCardNow, canTargetWithAttack, createGame, createSeatedPlayer, declineResponse, discardForHandLimit, drawCards, endTurn, getBaseDistanceBetweenPlayers, getDiscardRequirement, getPlayerById, getTopDiscardCard, isEquipmentCard, playAttack, playDodge, playEquipment, playHeal, respondToAttack, startTurn, type Card, type Character, type GameState, type Player, type Spectator } from '@wtk/game';

const viewerId='liu-bei';
const now='2026-01-01T20:10:00.000Z';
const character=(id:string,name:string):Character=>({id,name,hp:4,faction:'test',skills:[]});
const member=(id:string,username:string):Spectator=>({id,username,connectionStatus:'online',joinedAt:now,lastSeenAt:now});
const card=(id:string,name:string,effect:'attack'|'dodge'|'heal',suit:string,number:string):Card=>({id,name,type:'ไพ่พื้นฐาน',cardType:'basic',suit,number,image:null,description:null,effect,effectParams:{damage:1,heal_amount:1},triggerTiming:effect==='dodge'?'on_response':'on_play',equipmentSlot:null,createsResponseWindow:effect==='attack',conditions:null});
const equipmentCard=(id:string,name:string,cardType:'weapon'|'armor'|'offensive_mount'|'defensive_mount'):Card=>({id,name,type:'อุปกรณ์',cardType,suit:'♠',number:'A',image:null,description:null,effect:null,effectParams:{},triggerTiming:'passive',equipmentSlot:cardType,createsResponseWindow:false,conditions:null});

function createMockGameState():GameState {
  const state=createGame('local-combat',member(viewerId,'pakitta'),Array.from({length:42},(_,index)=>card(`draw-${index}`,'โจมตี','attack','♠','7')));
  const liuBei=createSeatedPlayer(member(viewerId,'pakitta'),4),caoCao=createSeatedPlayer(member('cao-cao','caocao_player'),2),sunQuan=createSeatedPlayer(member('sun-quan','sunquan'),1),zhaoYun=createSeatedPlayer(member('zhao-yun','zhaoyun_main'),3);
  liuBei.character=character('liu-bei','เล่าปี่'); liuBei.role='emperor'; liuBei.hp=liuBei.maxHp=4;
  caoCao.character=character('cao-cao','โจโฉ'); caoCao.hp=caoCao.maxHp=4;
  sunQuan.character=character('sun-quan','ซุนกวน'); sunQuan.hp=sunQuan.maxHp=3;
  zhaoYun.character=character('zhao-yun','จูล่ง'); zhaoYun.hp=1; zhaoYun.maxHp=4;
  liuBei.hand=[card('attack-1','โจมตี','attack','♥','7'),card('dodge-1','หลบ','dodge','♠','2'),card('heal-1','เสบียง','heal','♦','9'),card('attack-2','โจมตี','attack','♣','K'),card('dodge-2','หลบ','dodge','♠','5'),equipmentCard('weapon-old','ดาบเก่า','weapon'),equipmentCard('weapon-green-dragon','ง้าวมังกรเขียว','weapon'),equipmentCard('armor-eight','ค่ายกลแปดทิศ','armor'),equipmentCard('mount-offensive','ม้าศึก','offensive_mount'),equipmentCard('mount-defensive','ม้านั่ง','defensive_mount')];
  caoCao.hand=[card('cao-dodge','หลบ','dodge','♥','3')]; sunQuan.hand=[card('sun-heal','เสบียง','heal','♦','4')]; zhaoYun.hand=[card('zhao-heal','เสบียง','heal','♦','6')];
  state.players=[sunQuan,caoCao,zhaoYun,liuBei]; state.spectators=[]; state.phase='playing';
  state.discard=[card('previous-heal','เสบียง','heal','♦','9')];
  state.log=[
    {id:'log-1',at:'20:10',type:'started',message:'เริ่มเกมแล้ว'},
    {id:'log-2',at:'20:11',type:'roles',message:'แจกบทบาทให้ผู้เล่นแล้ว'},
    {id:'log-3',at:'20:12',type:'turn-start',message:'เล่าปี่ เริ่มเทิร์น'},
  ];
  startTurn(state,viewerId); return state;
}

const characterName=(player:Player|undefined)=>player?.character?.name??player?.username??'ผู้เล่น';
const hearts=(hp:number|undefined,maxHp:number|undefined)=><span className="mock-hearts">{'♥'.repeat(hp??0)}<i>{'♥'.repeat(Math.max(0,(maxHp??0)-(hp??0)))}</i></span>;

function edgePosition(index:number,total:number){const positions:Record<number,Array<[number,number]>>={3:[[50,1],[1,50],[99,50]],5:[[25,1],[50,1],[75,1],[1,50],[99,50]],7:[[20,1],[50,1],[80,1],[1,33],[1,67],[99,33],[99,67]],9:[[12,1],[31,1],[50,1],[69,1],[88,1],[1,33],[1,67],[99,33],[99,67]]};const [left,top]=positions[total]?.[index]??[50,1];return {left:`${left}%`,top:`${top}%`};}
function Equipment({ player }: { player: Player }) { const slot=(key:keyof Player['equipment'])=>player.equipment[key]; const render=(key:keyof Player['equipment'],icon:string,label:string)=><span className={`mock-equipment-slot ${slot(key)?'equipped':''}`} title={slot(key)?.name??`${label}: ว่าง`}><i>{icon}</i><em>{label}</em><b>{slot(key)?.name??'—'}</b></span>; return <div className="mock-equipment">{render('weapon','🗡','อาวุธ')}{render('armor','🛡','เกราะ')}{render('offensiveMount','🐎−','ม้ารุก')}{render('defensiveMount','🐎+','ม้ารับ')}</div>; }
function PlayerPanel({ player, distance, current, targetable, invalidTarget, onClick }: { player:Player; distance:number; current?:boolean; targetable?:boolean; invalidTarget?:boolean; onClick?:()=>void }) { return <article onClick={onClick} className={`mock-player ${current?'mock-self':''} ${player.id===viewerId?'':'local-opponent'} ${targetable?'local-targetable':''} ${invalidTarget?'local-out-of-range':''} ${!player.alive?'local-dead':''}`}><div className="mock-portrait">{characterName(player).slice(0,1)}</div><div className="mock-player-content"><b>{characterName(player)}</b><small className="mock-username">@{player.username}</small>{hearts(player.hp,player.maxHp)}<span className="mock-hand-count">🂠 × {player.hand.length}</span><small className="mock-debug">Seat {player.seatIndex} · Distance {distance}</small>{invalidTarget&&<small className="local-range-hint">ระยะไม่ถึง</small>}{current&&player.role&&<small className="mock-role">บทบาท: จักรพรรดิ</small>}<Equipment player={player}/></div></article>; }

export default function LocalGamePage(){
  const [gameState,setGameState]=useState<GameState>(()=>createMockGameState());
  const [selectedAttackId,setSelectedAttackId]=useState<string>();
  const [error,setError]=useState<string>();
  const update=(operation:(state:GameState)=>void)=>setGameState(current=>{const next=structuredClone(current) as GameState;try{operation(next);setError(undefined);return next}catch(cause){setError((cause as Error).message);return current}});
  const viewer=getPlayerById(gameState,viewerId)!;
  const opponents=gameState.players.filter(player=>player.id!==viewerId);
  const responseWindow=gameState.responseWindow,responderId=responseWindow?.currentResponderId;
  const responder=responderId?getPlayerById(gameState,responderId):undefined;
  const topDiscard=getTopDiscardCard(gameState);
  const action=gameState.currentAction;
  const actionActor=action?getPlayerById(gameState,action.actorId):undefined;
  const actionTarget=action?getPlayerById(gameState,action.targetIds[0]):undefined;
  const dyingPlayer=responseWindow?.type==='dying_heal'?getPlayerById(gameState,responseWindow.dyingPlayerId||''):undefined;
  const canRespond=Boolean(responseWindow&&responderId===viewerId);
  const canPlay=(card:Card)=>canPlayCardNow(gameState,viewerId,card)&&!(card.effect==='heal'&&(viewer.hp??0)>=(viewer.maxHp??0));
  const selectCard=(card:Card)=>{if(card.effect==='attack'&&canPlay(card))setSelectedAttackId(card.id);else if(card.effect==='dodge'&&canPlay(card))update(state=>playDodge(state,viewerId,card.id));else if(card.effect==='heal'&&canPlay(card))update(state=>playHeal(state,viewerId,card.id));else if(isEquipmentCard(card)&&canPlay(card))update(state=>playEquipment(state,viewerId,card.id));};
  const resolveDemo=(dodge:boolean)=>{if(!responder)return;const dodgeCard=responder.hand.find(card=>card.effect==='dodge');if(dodge){if(!dodgeCard){setError(`${characterName(responder)} ไม่มีไพ่หลบ`);return;}update(state=>playDodge(state,responder.id,dodgeCard.id));return;}update(state=>respondToAttack(state,responder.id));};
  const resolveDyingDemo=(heal:boolean)=>{if(!responder)return;const healCard=responder.hand.find(card=>card.effect==='heal');if(heal){if(!healCard){setError(`${characterName(responder)} ไม่มีไพ่เสบียง`);return;}update(state=>playHeal(state,responder.id,healCard.id));return;}update(state=>declineResponse(state,responder.id));};

  return <main className="mock-game-page local-game-page mock-count-4">
    <header className="mock-game-header"><div><small>Local combat prototype</small><h1>ยุทธพิชัยสามก๊ก</h1></div><p>Attack · Dodge · Heal</p><div className="local-turn-status"><b>ตา: {characterName(getPlayerById(gameState,gameState.turn.activePlayerId||''))}</b><span>Turn {gameState.turn.turnNumber} · {gameState.turn.phase}</span></div><button onClick={()=>{setGameState(createMockGameState());setSelectedAttackId(undefined);setError(undefined)}}>เริ่มใหม่</button></header>
    {error&&<p className="local-error">{error}</p>}
    <section className="mock-match-layout">
      <aside className="mock-side-panels"><section className="mock-log"><h2>บันทึกการเล่น</h2><div>{gameState.log.map(log=><p key={log.id}><time>{log.at.slice(11,16)||log.at}</time>{log.message}</p>)}</div></section><section className="mock-chat"><h2>แชท</h2><div><p><b>pakitta:</b> ขอคิดก่อนนะ</p><p><b>sunquan:</b> พร้อมแล้ว</p><p><b>caocao_player:</b> ใช้หลบไหม?</p></div></section></aside>
      <section className="mock-table-stage" data-density="large"><div className="mock-table-surface"><div className="mock-table-pattern">三國</div><section className="mock-piles"><article className="mock-pile"><div className="mock-deck">🂠</div><b>กองจั่ว</b><small>{gameState.drawPile.length} ใบ</small></article><article className="mock-pile"><div className="mock-discard">{topDiscard?<>{topDiscard.name}<br/><span>{topDiscard.rank} {topDiscard.suit}</span></>:'—'}</div><b>กองทิ้ง</b><small>{gameState.discardPile.length} ใบ</small></article></section>{action?<section className="mock-action"><small>การกระทำปัจจุบัน · {action.status}</small><p><b>{characterName(actionActor)}</b> ใช้ <b>{action.card?.name}</b> ใส่ <b>{characterName(actionTarget)}</b></p><article className="mock-action-card"><span>{action.card?.rank} {action.card?.suit}</span><strong>{action.card?.name}</strong><em>Attack</em></article></section>:<p className="local-action-empty">ยังไม่มีการกระทำ</p>}</div>{opponents.map((player,index)=>{const position=edgePosition(index,opponents.length);const style={'--seat-x':position.left,'--seat-y':position.top} as CSSProperties;const attackId=selectedAttackId,distance=getBaseDistanceBetweenPlayers(gameState,viewerId,player.id)??0,targetable=Boolean(attackId&&canTargetWithAttack(gameState,viewerId,player.id)),invalidTarget=Boolean(attackId&&player.alive&&!targetable);return <div key={player.id} className="mock-opponent" style={style}><PlayerPanel player={player} distance={distance} targetable={targetable} invalidTarget={invalidTarget} onClick={targetable&&attackId?()=>{update(state=>playAttack(state,viewerId,player.id,attackId));setSelectedAttackId(undefined)}:undefined}/></div>})}</section>
    </section>
    <section className="mock-current-player"><PlayerPanel player={viewer} distance={0} current/><div className="mock-your-turn">ไพ่ของคุณ {selectedAttackId?<strong>— เลือกผู้เล่นเป้าหมายบนโต๊ะ</strong>:<strong>— เลือกไพ่เพื่อเล่น</strong>}</div><div className="local-turn-controls"><button disabled={gameState.turn.activePlayerId!==viewerId||gameState.turn.phase!=='draw'} onClick={()=>update(state=>drawCards(state,viewerId,2))}>จั่ว 2 ใบ</button><button disabled={gameState.turn.activePlayerId!==viewerId||Boolean(gameState.responseWindow)} onClick={()=>update(state=>endTurn(state,viewerId))}>จบเทิร์น</button>{getDiscardRequirement(gameState,viewerId)>0&&gameState.turn.activePlayerId===viewerId&&<button className="mock-muted-button" onClick={()=>update(state=>{const required=getDiscardRequirement(state,viewerId);discardForHandLimit(state,viewerId,state.players.find(player=>player.id===viewerId)!.hand.slice(0,required).map(card=>card.id));})}>ทิ้งไพ่เกินมือ ({getDiscardRequirement(gameState,viewerId)})</button>}</div>{selectedAttackId&&<button className="local-cancel" onClick={()=>setSelectedAttackId(undefined)}>ยกเลิกเลือกเป้าหมาย</button>}<div className="mock-hand">{viewer.hand.map(card=><article key={card.id} onClick={()=>selectCard(card)} className={`mock-card mock-card-${card.effect==='attack'?'red':card.effect==='dodge'?'blue':'gold'} ${canPlay(card)?'local-hand-card':'local-card-disabled'} ${selectedAttackId===card.id?'selected-card':''}`}><header><span>{card.number}</span><span>{card.suit}</span></header><div className="mock-card-art">WTK</div><b>{card.name}</b><small>{card.type}</small></article>)}</div></section>
    {responseWindow&&<section className="mock-response" role="dialog"><span className="mock-response-icon">⚔</span>{responseWindow.type==='dying_heal'?<>{canRespond?<><div><small>{characterName(dyingPlayer)} อยู่ในสถานะใกล้ตาย</small><h2>ใช้ เสบียง ช่วยหรือไม่?</h2><p>ช่วย {characterName(dyingPlayer)} ให้รอดจากการตาย</p></div><div className="mock-response-actions"><button disabled={!viewer.hand.some(card=>card.effect==='heal')} onClick={()=>{const heal=viewer.hand.find(card=>card.effect==='heal');if(heal)update(state=>playHeal(state,viewerId,heal.id))}}>✚ ใช้ เสบียง</button><button className="mock-muted-button" onClick={()=>update(state=>declineResponse(state,viewerId))}>ไม่ทำอะไร</button></div></>:<><div><small>Dying Rescue</small><h2>กำลังรอ {characterName(responder)}</h2><p>ว่าจะใช้ เสบียง ช่วย {characterName(dyingPlayer)} หรือไม่</p></div><div className="mock-response-actions local-demo-actions"><button disabled={!responder?.hand.some(card=>card.effect==='heal')} onClick={()=>resolveDyingDemo(true)}>Demo: ใช้ เสบียง</button><button className="mock-muted-button" onClick={()=>resolveDyingDemo(false)}>Demo: ไม่ทำอะไร</button></div></>}</>:<>{canRespond?<><div><small>{characterName(actionActor)} ใช้ไพ่</small><h2>โจมตี ใส่คุณ</h2><p>คุณต้องการตอบโต้อย่างไร?</p></div><div className="mock-response-actions"><button disabled={!viewer.hand.some(card=>card.effect==='dodge')} onClick={()=>{const dodge=viewer.hand.find(card=>card.effect==='dodge');if(dodge)update(state=>playDodge(state,viewerId,dodge.id))}}>🛡 ใช้ หลบ</button><button className="mock-muted-button" onClick={()=>update(state=>respondToAttack(state,viewerId))}>ไม่ทำอะไร</button></div></>:<><div><small>Response Window</small><h2>กำลังรอ {characterName(responder)} ตอบสนอง</h2><p>คุณไม่ใช่ผู้ตอบสนองใน action นี้</p></div><div className="mock-response-actions local-demo-actions"><button disabled={!responder?.hand.some(card=>card.effect==='dodge')} onClick={()=>resolveDemo(true)}>Demo: ใช้ หลบ</button><button className="mock-muted-button" onClick={()=>resolveDemo(false)}>Demo: ไม่ทำอะไร</button></div></>}</>}</section>}
  </main>;
}
