'use client';

import { useState, type CSSProperties } from 'react';
import { attackIgnoresTargetArmor, canPlayCardNow, canTargetWithAttack, continueRepeatAttackAfterDodge, createGame, createSeatedPlayer, declineDestroyTargetMount, declineForceAttackDamage, declineMassResponse, declineRepeatAttackAfterDodge, declineResponse, destroyTargetMountAfterDamage, discardForHandLimit, drawCards, endTurn, forceAttackDamageByDiscardingTwo, getBaseDistanceBetweenPlayers, getEffectiveDistanceBetweenPlayers, getDiscardRequirement, getPlayerById, getTopDiscardCard, hasUnlimitedAttackPerTurn, isEquipmentCard, playAttack, playAttackResponse, playDiscardTargetCard, playDodge, playDrawCardsTrick, playEquipment, playHeal, playHealAllLiving, playMassAttackOrDamage, playMassDodgeOrDamage, playMassResponseCard, playStealTargetCard, respondToAttack, startTurn, type Card, type Character, type GameState, type Player, type Spectator, useArmorJudgment } from '@wtk/game';

const viewerId='liu-bei';
const now='2026-01-01T20:10:00.000Z';
const character=(id:string,name:string):Character=>({id,name,hp:4,faction:'test',skills:[]});
const member=(id:string,username:string):Spectator=>({id,username,connectionStatus:'online',joinedAt:now,lastSeenAt:now});
const card=(id:string,name:string,effect:'attack'|'dodge'|'heal',suit:string,number:string):Card=>({id,name,type:'ไพ่พื้นฐาน',cardType:'basic',suit,number,image:null,description:null,effect,effectParams:{damage:1,heal_amount:1},triggerTiming:effect==='dodge'?'on_response':'on_play',equipmentSlot:null,createsResponseWindow:effect==='attack',conditions:null});
const equipmentCard=(id:string,name:string,cardType:'weapon'|'armor'|'offensive_mount'|'defensive_mount',effectParams:Record<string,unknown>={}):Card=>({id,name,type:'อุปกรณ์',cardType,suit:'♠',number:'A',image:null,description:null,effect:null,effectParams,triggerTiming:'passive',equipmentSlot:cardType,createsResponseWindow:false,conditions:null});
const discardTargetCard=(id:string):Card=>({id,name:'ถอนสะพาน',type:'อุบาย',cardType:'instant_trick',suit:'♣',number:'3',image:null,description:null,effect:'discard_target_card',effectParams:{amount:1},triggerTiming:'on_play',equipmentSlot:null,createsResponseWindow:false,conditions:null});
const stealTargetCard=(id:string):Card=>({id,name:'ลอบขโมย',type:'อุบาย',cardType:'instant_trick',suit:'♠',number:'4',image:null,description:null,effect:'steal_target_card_in_range',effectParams:{range:1},triggerTiming:'on_play',equipmentSlot:null,createsResponseWindow:false,conditions:null});
const duelCard=(id:string):Card=>({id,name:'ท้าสู้',type:'อุบาย',cardType:'instant_trick',suit:'♠',number:'A',image:null,description:null,effect:'duel_attack_response',effectParams:{damage:1},triggerTiming:'on_play',equipmentSlot:null,createsResponseWindow:true,conditions:null});
const massCard=(id:string,name:string,effect:'all_others_dodge_or_damage'|'all_others_attack_or_damage'):Card=>({id,name,type:'อุบาย',cardType:'instant_trick',suit:'♥',number:'A',image:null,description:null,effect,effectParams:{damage:1},triggerTiming:'on_play',equipmentSlot:null,createsResponseWindow:true,conditions:null});

const immediateTrick=(id:string,name:string,effect:'draw_cards'|'heal_all_living',effectParams:Record<string,unknown>={}):Card=>({id,name,type:'อุบาย',cardType:'instant_trick',suit:'♥',number:'A',image:null,description:null,effect,effectParams,triggerTiming:'on_play',equipmentSlot:null,createsResponseWindow:false,conditions:null});

function createMockGameState():GameState {
  const state=createGame('local-combat',member(viewerId,'pakitta'),Array.from({length:42},(_,index)=>card(`draw-${index}`,'โจมตี','attack','♠','7')));
  const liuBei=createSeatedPlayer(member(viewerId,'pakitta'),4),caoCao=createSeatedPlayer(member('cao-cao','caocao_player'),2),sunQuan=createSeatedPlayer(member('sun-quan','sunquan'),1),zhaoYun=createSeatedPlayer(member('zhao-yun','zhaoyun_main'),3);
  liuBei.character=character('liu-bei','เล่าปี่'); liuBei.role='emperor'; liuBei.hp=liuBei.maxHp=4;
  caoCao.character=character('cao-cao','โจโฉ'); caoCao.hp=caoCao.maxHp=4;
  sunQuan.character=character('sun-quan','ซุนกวน'); sunQuan.hp=sunQuan.maxHp=3;
  zhaoYun.character=character('zhao-yun','จูล่ง'); zhaoYun.hp=1; zhaoYun.maxHp=4;
  liuBei.hand=[card('attack-1','โจมตี','attack','♥','7'),card('dodge-1','หลบ','dodge','♠','2'),card('heal-1','เสบียง','heal','♦','9'),card('attack-2','โจมตี','attack','♣','K'),card('dodge-2','หลบ','dodge','♠','5'),discardTargetCard('discard-bridge'),stealTargetCard('steal-ambush'),equipmentCard('weapon-old','ดาบเก่า','weapon'),equipmentCard('weapon-green-dragon','ง้าวมังกรเขียว','weapon',{range:3}),equipmentCard('armor-eight','ค่ายกลแปดทิศ','armor'),equipmentCard('mount-offensive','ม้าศึก','offensive_mount'),equipmentCard('mount-defensive','ม้านั่ง','defensive_mount')];
  caoCao.hand=[card('cao-dodge','หลบ','dodge','♥','3'),card('cao-attack','โจมตี','attack','♠','8'),card('cao-heal','เสบียง','heal','♦','Q')];
  sunQuan.hand=[card('sun-heal','เสบียง','heal','♦','4'),card('sun-attack','โจมตี','attack','♣','6'),card('sun-dodge','หลบ','dodge','♥','J'),card('sun-attack-2','โจมตี','attack','♠','9')];
  zhaoYun.hand=[card('zhao-heal','เสบียง','heal','♦','6'),card('zhao-dodge','หลบ','dodge','♠','7'),card('zhao-attack','โจมตี','attack','♣','10'),card('zhao-dodge-2','หลบ','dodge','♥','2'),card('zhao-attack-2','โจมตี','attack','♠','K')];
  caoCao.equipment.weapon=equipmentCard('cao-weapon','กระบี่ชิงกัง','weapon',{range:2});sunQuan.equipment.armor=equipmentCard('sun-armor','ค่ายกลแปดทิศ','armor');zhaoYun.equipment.offensiveMount=equipmentCard('zhao-mount','ม้าศึก','offensive_mount');
  liuBei.hand.push(immediateTrick('draw-cards','จั่วการ์ด','draw_cards',{amount:2}),immediateTrick('heal-all','ร่วมสาบาน','heal_all_living'),duelCard('duel-card'),massCard('arrow','เกาทัณฑ์พันดอก','all_others_dodge_or_damage'),massCard('barbarian','คนเถื่อนบุกรุก','all_others_attack_or_damage'),{...equipmentCard('crossbow','หน้าไม้กล','weapon'),effect:'unlimited_attack_per_turn'},{...equipmentCard('green-dragon-repeat','ง้าวมังกรเขียว','weapon'),effect:'repeat_attack_after_dodge'},{...equipmentCard('qinggang','กระบี่ชิงกัง','weapon'),effect:'ignore_target_armor'},{...equipmentCard('kirin-bow','ธนูกิเลน','weapon'),effect:'damage_destroy_target_mount'},{...equipmentCard('axe','ขวานก้วนสื่อ','weapon'),effect:'discard_two_force_attack_damage'});
  liuBei.equipment.armor={...equipmentCard('liu-judgment-armor','ค่ายกลแปดทิศ','armor'),effect:'judgment_dodge'};
  state.players=[sunQuan,caoCao,zhaoYun,liuBei]; state.spectators=[]; state.phase='playing';
  state.discard=[card('previous-heal','เสบียง','heal','♦','9')];
  state.log=[
    {id:'log-1',at:'20:10',type:'started',message:'เริ่มเกมแล้ว'},
    {id:'log-2',at:'20:11',type:'roles',message:'แจกบทบาทให้ผู้เล่นแล้ว'},
    {id:'log-3',at:'20:12',type:'turn-start',message:'เล่าปี่ เริ่มเทิร์น'},
  ];
  startTurn(state,viewerId); return state;
}

const characterName=(player:Player|undefined)=>player?.character?.name??player?.username??'ผู้เล่น';
const hearts=(hp:number|undefined,maxHp:number|undefined)=><span className="mock-hearts">{'♥'.repeat(hp??0)}<i>{'♥'.repeat(Math.max(0,(maxHp??0)-(hp??0)))}</i></span>;

function edgePosition(index:number,total:number){const positions:Record<number,Array<[number,number]>>={3:[[50,1],[1,50],[99,50]],5:[[25,1],[50,1],[75,1],[1,50],[99,50]],7:[[20,1],[50,1],[80,1],[1,33],[1,67],[99,33],[99,67]],9:[[12,1],[31,1],[50,1],[69,1],[88,1],[1,33],[1,67],[99,33],[99,67]]};const [left,top]=positions[total]?.[index]??[50,1];return {left:`${left}%`,top:`${top}%`};}
function Equipment({ player }: { player: Player }) { const slot=(key:keyof Player['equipment'])=>player.equipment[key]; const render=(key:keyof Player['equipment'],icon:string,label:string)=><span className={`mock-equipment-slot ${slot(key)?'equipped':''}`} title={slot(key)?.name??`${label}: ว่าง`}><i>{icon}</i><em>{label}</em><b>{slot(key)?.name??'—'}</b></span>; return <div className="mock-equipment">{render('weapon','🗡','อาวุธ')}{render('armor','🛡','เกราะ')}{render('offensiveMount','🐎−','ม้ารุก')}{render('defensiveMount','🐎+','ม้ารับ')}</div>; }
function PlayerPanel({ player, distance, baseDistance, attackRange, current, targetable, invalidTarget, onClick }: { player:Player; distance:number; baseDistance?:number; attackRange?:number; current?:boolean; targetable?:boolean; invalidTarget?:boolean; onClick?:()=>void }) { const equippedRange=player.equipment.weapon?.effectParams.range;const displayedAttackRange=attackRange??(typeof equippedRange==='number'&&equippedRange>0?equippedRange:1);return <article onClick={onClick} className={`mock-player ${current?'mock-self':''} ${player.id===viewerId?'':'local-opponent'} ${targetable?'local-targetable':''} ${invalidTarget?'local-out-of-range':''} ${!player.alive?'local-dead':''}`}><div className="mock-portrait">{characterName(player).slice(0,1)}</div><div className="mock-player-content"><b>{characterName(player)}</b><small className="mock-username">@{player.username}</small>{hearts(player.hp,player.maxHp)}<span className="mock-hand-count">🂠 × {player.hand.length}</span><small className="mock-debug">Seat {player.seatIndex} · ระยะ {distance}{baseDistance!==undefined&&baseDistance!==distance?` (ฐาน ${baseDistance})`:''}</small>{invalidTarget&&<small className="local-range-hint">ระยะไม่ถึง</small>}{current&&player.role&&<small className="mock-role">บทบาท: จักรพรรดิ</small>}{current&&<small className="mock-role">ระยะโจมตี: {displayedAttackRange}</small>}<Equipment player={player}/></div></article>; }

export default function LocalGamePage(){
  const [gameState,setGameState]=useState<GameState>(()=>createMockGameState());
  const [selectedAttackId,setSelectedAttackId]=useState<string>();
  const [selectedDiscardCardId,setSelectedDiscardCardId]=useState<string>();
  const [selectedDiscardTargetId,setSelectedDiscardTargetId]=useState<string>();
  const [selectedDiscardZone,setSelectedDiscardZone]=useState<'hand'|'equipment'>();
  const [selectedStealCardId,setSelectedStealCardId]=useState<string>();
  const [selectedStealTargetId,setSelectedStealTargetId]=useState<string>();
  const [selectedStealZone,setSelectedStealZone]=useState<'hand'|'equipment'>();
  const [pendingEquipmentId,setPendingEquipmentId]=useState<string>();
  const [notice,setNotice]=useState<string>();
  const [forceDiscardRefs,setForceDiscardRefs]=useState<string[]>([]);
  const [error,setError]=useState<string>();
  const update=(operation:(state:GameState)=>void)=>setGameState(current=>{const next=structuredClone(current) as GameState;try{operation(next);setError(undefined);return next}catch(cause){setError((cause as Error).message);return current}});
  const viewer=getPlayerById(gameState,viewerId)!;
  const opponents=gameState.players.filter(player=>player.id!==viewerId);
  const responseWindow=gameState.responseWindow,responderId=responseWindow?.currentResponderId;
  const responder=responderId?getPlayerById(gameState,responderId):undefined;
  const topDiscard=getTopDiscardCard(gameState);
  const action=gameState.currentAction;
  const actionActor=action?getPlayerById(gameState,action.actorId):undefined;
  const actionTarget=action?getPlayerById(gameState,action.targetIds[0]):undefined;
  const dyingPlayer=responseWindow?.type==='dying_heal'?getPlayerById(gameState,responseWindow.dyingPlayerId||''):undefined;
  const canRespond=Boolean(responseWindow&&responderId===viewerId);
  const canPlay=(card:Card)=>canPlayCardNow(gameState,viewerId,card)&&!(card.effect==='heal'&&(viewer.hp??0)>=(viewer.maxHp??0));
  const hasSelectableEquipment=(player:Player)=>Object.values(player.equipment).some(Boolean);
  const hasSelectableZone=(player:Player)=>player.hand.length>0||hasSelectableEquipment(player);
  const discardTarget=selectedDiscardTargetId?getPlayerById(gameState,selectedDiscardTargetId):undefined;
  const stealTarget=selectedStealTargetId?getPlayerById(gameState,selectedStealTargetId):undefined;
  const pendingEquipment=pendingEquipmentId?viewer.hand.find(card=>card.id===pendingEquipmentId):undefined;
  const pendingSlot=pendingEquipment?.cardType==='weapon'?'weapon':pendingEquipment?.cardType==='armor'?'armor':pendingEquipment?.cardType==='offensive_mount'?'offensiveMount':pendingEquipment?.cardType==='defensive_mount'?'defensiveMount':undefined;
  const replacedEquipment=pendingSlot?viewer.equipment[pendingSlot]:undefined;
  const selectCard=(card:Card)=>{if((card.effect==='dodge'||card.effect==='attack')&&(responseWindow?.type==='mass_dodge'||responseWindow?.type==='mass_attack')&&canPlay(card))update(state=>playMassResponseCard(state,viewerId,card.id));else if(card.effect==='attack'&&responseWindow?.type==='duel_attack'&&canPlay(card))update(state=>playAttackResponse(state,viewerId,card.id));else if((card.effect==='attack'||card.effect==='duel_attack_response')&&canPlay(card)){if(card.effect==='attack'&&gameState.turn.attackUsedThisTurn>=1&&!hasUnlimitedAttackPerTurn(gameState,viewerId)){setNotice('คุณใช้ โจมตี ไปแล้วในรอบนี้');return;}setSelectedAttackId(card.id);setSelectedDiscardCardId(undefined);setSelectedStealCardId(undefined);}else if(card.effect==='all_others_dodge_or_damage'&&canPlay(card))update(state=>playMassDodgeOrDamage(state,viewerId,card.id));else if(card.effect==='all_others_attack_or_damage'&&canPlay(card))update(state=>playMassAttackOrDamage(state,viewerId,card.id));else if(card.effect==='discard_target_card'&&canPlay(card)){setSelectedDiscardCardId(card.id);setSelectedAttackId(undefined);setSelectedStealCardId(undefined);}else if(card.effect==='steal_target_card_in_range'&&canPlay(card)){setSelectedStealCardId(card.id);setSelectedAttackId(undefined);setSelectedDiscardCardId(undefined);}else if(card.effect==='draw_cards'&&canPlay(card))update(state=>playDrawCardsTrick(state,viewerId,card.id));else if(card.effect==='heal_all_living'&&canPlay(card))update(state=>playHealAllLiving(state,viewerId,card.id));else if(card.effect==='dodge'&&canPlay(card))update(state=>playDodge(state,viewerId,card.id));else if(card.effect==='heal'&&canPlay(card))update(state=>playHeal(state,viewerId,card.id));else if(isEquipmentCard(card)&&canPlay(card))setPendingEquipmentId(card.id);};
  const resolveDemo=(dodge:boolean)=>{if(!responder)return;const dodgeCard=responder.hand.find(card=>card.effect==='dodge');if(dodge){if(!dodgeCard){setError(`${characterName(responder)} ไม่มีไพ่หลบ`);return;}update(state=>playDodge(state,responder.id,dodgeCard.id));return;}update(state=>respondToAttack(state,responder.id));};
  const resolveDyingDemo=(heal:boolean)=>{if(!responder)return;const healCard=responder.hand.find(card=>card.effect==='heal');if(heal){if(!healCard){setError(`${characterName(responder)} ไม่มีไพ่เสบียง`);return;}update(state=>playHeal(state,responder.id,healCard.id));return;}update(state=>declineResponse(state,responder.id));};

  return <main className="mock-game-page local-game-page mock-count-4">
    <header className="mock-game-header"><div><small>Local combat prototype</small><h1>ยุทธพิชัยสามก๊ก</h1></div><p>Attack · Dodge · Heal</p><div className="local-turn-status"><b>ตา: {characterName(getPlayerById(gameState,gameState.turn.activePlayerId||''))}</b><span>Turn {gameState.turn.turnNumber} · {gameState.turn.phase}</span></div><button onClick={()=>{setGameState(createMockGameState());setSelectedAttackId(undefined);setError(undefined)}}>เริ่มใหม่</button></header>
    {notice&&<aside className="local-notice" role="status"><span>{notice}</span><button onClick={()=>setNotice(undefined)} aria-label="ปิดข้อความแจ้งเตือน">×</button></aside>}
    {error&&<p className="local-error">{error}</p>}
    <section className="mock-match-layout">
      <aside className="mock-side-panels"><section className="mock-log"><h2>บันทึกการเล่น</h2><div>{gameState.log.map(log=><p key={log.id}><time>{log.at.slice(11,16)||log.at}</time>{log.message}</p>)}</div></section><section className="mock-chat"><h2>แชท</h2><div><p><b>pakitta:</b> ขอคิดก่อนนะ</p><p><b>sunquan:</b> พร้อมแล้ว</p><p><b>caocao_player:</b> ใช้หลบไหม?</p></div></section></aside>
      <section className="mock-table-stage" data-density="large"><div className="mock-table-surface"><div className="mock-table-pattern">三國</div><section className="mock-piles"><article className="mock-pile"><div className="mock-deck">🂠</div><b>กองจั่ว</b><small>{gameState.drawPile.length} ใบ</small></article><article className="mock-pile"><div className="mock-discard">{topDiscard?<>{topDiscard.name}<br/><span>{topDiscard.rank} {topDiscard.suit}</span></>:'—'}</div><b>กองทิ้ง</b><small>{gameState.discardPile.length} ใบ</small></article></section>{action?<section className="mock-action"><small>การกระทำปัจจุบัน · {action.status}</small><p><b>{characterName(actionActor)}</b> ใช้ <b>{action.card?.name}</b> ใส่ <b>{characterName(actionTarget)}</b></p><article className="mock-action-card"><span>{action.card?.rank} {action.card?.suit}</span><strong>{action.card?.name}</strong><em>Attack</em></article></section>:<p className="local-action-empty">ยังไม่มีการกระทำ</p>}</div>{opponents.map((player,index)=>{const position=edgePosition(index,opponents.length);const style={'--seat-x':position.left,'--seat-y':position.top} as CSSProperties;const attackId=selectedAttackId,discardId=selectedDiscardCardId,stealId=selectedStealCardId,baseDistance=getBaseDistanceBetweenPlayers(gameState,viewerId,player.id)??0,distance=getEffectiveDistanceBetweenPlayers(gameState,viewerId,player.id)??0,attackTarget=Boolean(attackId&&canTargetWithAttack(gameState,viewerId,player.id)),discardTargetable=Boolean(discardId&&player.alive&&hasSelectableZone(player)),stealTargetable=Boolean(stealId&&hasSelectableZone(player)&&player.alive&&distance<=1),targetable=attackTarget||discardTargetable||stealTargetable,invalidTarget=Boolean((attackId&&player.alive&&!attackTarget)||(discardId&&player.alive&&!discardTargetable)||(stealId&&player.alive&&!stealTargetable));const onTarget=attackTarget&&attackId?()=>{update(state=>playAttack(state,viewerId,player.id,attackId));setSelectedAttackId(undefined)}:discardTargetable?()=>{setSelectedDiscardTargetId(player.id);setSelectedDiscardZone(undefined)}:stealTargetable?()=>{setSelectedStealTargetId(player.id);setSelectedStealZone(undefined)}:undefined;return <div key={player.id} className="mock-opponent" style={style}><PlayerPanel player={player} distance={distance} baseDistance={baseDistance} targetable={targetable} invalidTarget={invalidTarget} onClick={onTarget}/></div>})}</section>
    </section>
    <section className="mock-current-player"><PlayerPanel player={viewer} distance={0} current/><div className="mock-your-turn">ไพ่ของคุณ {selectedAttackId||selectedDiscardCardId||selectedStealCardId?<strong>— เลือกผู้เล่นเป้าหมายบนโต๊ะ</strong>:<strong>— เลือกไพ่เพื่อเล่น</strong>}</div><div className="local-turn-controls"><button disabled={gameState.turn.activePlayerId!==viewerId||gameState.turn.phase!=='draw'} onClick={()=>update(state=>drawCards(state,viewerId,2))}>จั่ว 2 ใบ</button><button disabled={gameState.turn.activePlayerId!==viewerId||Boolean(gameState.responseWindow)} onClick={()=>update(state=>endTurn(state,viewerId))}>จบเทิร์น</button>{getDiscardRequirement(gameState,viewerId)>0&&gameState.turn.activePlayerId===viewerId&&<button className="mock-muted-button" onClick={()=>update(state=>{const required=getDiscardRequirement(state,viewerId);discardForHandLimit(state,viewerId,state.players.find(player=>player.id===viewerId)!.hand.slice(0,required).map(card=>card.id));})}>ทิ้งไพ่เกินมือ ({getDiscardRequirement(gameState,viewerId)})</button>}</div>{(selectedAttackId||selectedDiscardCardId||selectedStealCardId)&&<button className="local-cancel" onClick={()=>{setSelectedAttackId(undefined);setSelectedDiscardCardId(undefined);setSelectedDiscardTargetId(undefined);setSelectedStealCardId(undefined);setSelectedStealTargetId(undefined)}}>ยกเลิกเลือกเป้าหมาย</button>}<div className="mock-hand">{viewer.hand.map(card=><article key={card.id} onClick={()=>selectCard(card)} className={`mock-card mock-card-${card.effect==='attack'?'red':card.effect==='dodge'?'blue':'gold'} ${canPlay(card)?'local-hand-card':'local-card-disabled'} ${selectedAttackId===card.id||selectedDiscardCardId===card.id||selectedStealCardId===card.id?'selected-card':''}`}><header><span>{card.number}</span><span>{card.suit}</span></header><div className="mock-card-art">WTK</div><b>{card.name}</b><small>{card.type}</small></article>)}</div></section>
    {selectedDiscardCardId&&discardTarget&&<div className="modal-backdrop"><section className="card-detail local-target-picker"><h2>เลือกไพ่ของ {characterName(discardTarget)}</h2>{!selectedDiscardZone?<><p>เลือกโซน</p><div className="local-equipment-picker"><button disabled={!discardTarget.hand.length} onClick={()=>setSelectedDiscardZone('hand')}>🂠 มือ ({discardTarget.hand.length})</button><button disabled={!hasSelectableEquipment(discardTarget)} onClick={()=>setSelectedDiscardZone('equipment')}>อุปกรณ์ ({Object.values(discardTarget.equipment).filter(Boolean).length})</button><button disabled>พื้นที่ตัดสิน (0)</button></div></>:selectedDiscardZone==='hand'?<><p>เลือกไพ่บนมือที่ต้องการทิ้ง</p><div className="local-equipment-picker">{Array.from({length:discardTarget.hand.length},(_,handIndex)=><button key={handIndex} onClick={()=>{update(state=>playDiscardTargetCard(state,viewerId,discardTarget.id,selectedDiscardCardId,{zone:'hand',handIndex}));setSelectedDiscardCardId(undefined);setSelectedDiscardTargetId(undefined);setSelectedDiscardZone(undefined)}}>🂠 {handIndex+1}</button>)}</div></>:<><p>เลือกอุปกรณ์ที่ต้องการทิ้ง</p><div className="local-equipment-picker">{([{key:'weapon',label:'อาวุธ'},{key:'armor',label:'เกราะ'},{key:'offensiveMount',label:'ม้ารุก'},{key:'defensiveMount',label:'ม้ารับ'}] as const).map(({key,label})=>{const equipment=discardTarget.equipment[key];return equipment?<button key={key} onClick={()=>{update(state=>playDiscardTargetCard(state,viewerId,discardTarget.id,selectedDiscardCardId,{zone:'equipment',cardInstanceId:equipment.id}));setSelectedDiscardCardId(undefined);setSelectedDiscardTargetId(undefined);setSelectedDiscardZone(undefined)}}><small>{label}</small>{equipment.name}</button>:<span key={key} className="local-empty-slot">{label}: ว่าง</span>})}</div></>}<button className="mock-muted-button" onClick={()=>{setSelectedDiscardCardId(undefined);setSelectedDiscardTargetId(undefined);setSelectedDiscardZone(undefined)}}>ยกเลิก</button></section></div>}
    {selectedStealCardId&&stealTarget&&<div className="modal-backdrop"><section className="card-detail local-target-picker"><h2>เลือกไพ่ของ {characterName(stealTarget)}</h2>{!selectedStealZone?<><p>เลือกโซน</p><div className="local-equipment-picker"><button disabled={!stealTarget.hand.length} onClick={()=>setSelectedStealZone('hand')}>🂠 มือ ({stealTarget.hand.length})</button><button disabled={!hasSelectableEquipment(stealTarget)} onClick={()=>setSelectedStealZone('equipment')}>อุปกรณ์ ({Object.values(stealTarget.equipment).filter(Boolean).length})</button><button disabled>พื้นที่ตัดสิน (0)</button></div></>:selectedStealZone==='hand'?<><p>เลือกไพ่บนมือที่ต้องการขโมย</p><div className="local-equipment-picker">{Array.from({length:stealTarget.hand.length},(_,handIndex)=><button key={handIndex} onClick={()=>{update(state=>playStealTargetCard(state,viewerId,stealTarget.id,{zone:'hand',handIndex},selectedStealCardId));setSelectedStealCardId(undefined);setSelectedStealTargetId(undefined);setSelectedStealZone(undefined)}}>🂠 {handIndex+1}</button>)}</div></>:<><p>เลือกอุปกรณ์ที่ต้องการขโมย</p><div className="local-equipment-picker">{([{key:'weapon',label:'อาวุธ'},{key:'armor',label:'เกราะ'},{key:'offensiveMount',label:'ม้ารุก'},{key:'defensiveMount',label:'ม้ารับ'}] as const).map(({key,label})=>{const equipment=stealTarget.equipment[key];return equipment?<button key={key} onClick={()=>{update(state=>playStealTargetCard(state,viewerId,stealTarget.id,{zone:'equipment',cardInstanceId:equipment.id},selectedStealCardId));setSelectedStealCardId(undefined);setSelectedStealTargetId(undefined);setSelectedStealZone(undefined)}}><small>{label}</small>{equipment.name}</button>:<span key={key} className="local-empty-slot">{label}: ว่าง</span>})}</div></>}<button className="mock-muted-button" onClick={()=>{setSelectedStealCardId(undefined);setSelectedStealTargetId(undefined);setSelectedStealZone(undefined)}}>ยกเลิก</button></section></div>}
    {responseWindow&&<section className="mock-response" role="dialog"><span className="mock-response-icon">⚔</span>{responseWindow.type==='dying_heal'?<>{canRespond?<><div><small>{characterName(dyingPlayer)} อยู่ในสถานะใกล้ตาย</small><h2>ใช้ เสบียง ช่วยหรือไม่?</h2><p>ช่วย {characterName(dyingPlayer)} ให้รอดจากการตาย</p></div><div className="mock-response-actions"><button disabled={!viewer.hand.some(card=>card.effect==='heal')} onClick={()=>{const heal=viewer.hand.find(card=>card.effect==='heal');if(heal)update(state=>playHeal(state,viewerId,heal.id))}}>✚ ใช้ เสบียง</button><button className="mock-muted-button" onClick={()=>update(state=>declineResponse(state,viewerId))}>ไม่ทำอะไร</button></div></>:<><div><small>Dying Rescue</small><h2>กำลังรอ {characterName(responder)}</h2><p>ว่าจะใช้ เสบียง ช่วย {characterName(dyingPlayer)} หรือไม่</p></div><div className="mock-response-actions local-demo-actions"><button disabled={!responder?.hand.some(card=>card.effect==='heal')} onClick={()=>resolveDyingDemo(true)}>Demo: ใช้ เสบียง</button><button className="mock-muted-button" onClick={()=>resolveDyingDemo(false)}>Demo: ไม่ทำอะไร</button></div></>}</>:<>{canRespond?<><div><small>{characterName(actionActor)} ใช้ไพ่</small><h2>โจมตี ใส่คุณ</h2><p>คุณต้องการตอบโต้อย่างไร?</p></div><div className="mock-response-actions"><button disabled={!viewer.hand.some(card=>card.effect==='dodge')} onClick={()=>{const dodge=viewer.hand.find(card=>card.effect==='dodge');if(dodge)update(state=>playDodge(state,viewerId,dodge.id))}}>🛡 ใช้ หลบ</button><button className="mock-muted-button" onClick={()=>update(state=>respondToAttack(state,viewerId))}>ไม่ทำอะไร</button></div></>:<><div><small>Response Window</small><h2>กำลังรอ {characterName(responder)} ตอบสนอง</h2><p>คุณไม่ใช่ผู้ตอบสนองใน action นี้</p></div><div className="mock-response-actions local-demo-actions"><button disabled={!responder?.hand.some(card=>card.effect==='dodge')} onClick={()=>resolveDemo(true)}>Demo: ใช้ หลบ</button><button className="mock-muted-button" onClick={()=>resolveDemo(false)}>Demo: ไม่ทำอะไร</button></div></>}</>}</section>}
    {pendingEquipment&&<div className="modal-backdrop"><section className="card-detail local-equipment-confirm"><h2>{replacedEquipment?'เปลี่ยนอุปกรณ์หรือไม่?':'ติดตั้งอุปกรณ์หรือไม่?'}</h2>{replacedEquipment?<p>คุณมี {replacedEquipment.name} อยู่แล้ว<br/>ต้องการเปลี่ยนเป็น <b>{pendingEquipment.name}</b> หรือไม่?</p>:<p>ติดตั้ง <b>{pendingEquipment.name}</b> หรือไม่?</p>}<div className="mock-response-actions"><button onClick={()=>{update(state=>playEquipment(state,viewerId,pendingEquipment.id));setPendingEquipmentId(undefined)}}>{replacedEquipment?'เปลี่ยน':'ติดตั้ง'}</button><button className="mock-muted-button" onClick={()=>setPendingEquipmentId(undefined)}>ยกเลิก</button></div></section></div>}
    {responseWindow?.type==='attack_dodge'&&canRespond&&responder?.equipment.armor?.effect==='judgment_dodge'&&!attackIgnoresTargetArmor(gameState,actionActor?.id||'')&&<section className="local-armor-judgment" role="status"><b>คุณสามารถใช้เกราะตัดสินได้</b><button onClick={()=>update(state=>useArmorJudgment(state,responder.id))}>ใช้เกราะตัดสิน</button></section>}
    {gameState.pendingRepeatAttack&&(()=>{const pending=gameState.pendingRepeatAttack,attacker=getPlayerById(gameState,pending.attackerId),attack=attacker?.hand.find(card=>card.effect==='attack');return <section className="local-repeat-attack" role="dialog"><b>เป้าหมายหลบสำเร็จ ต้องการโจมตีซ้ำด้วย {pending.weaponName} หรือไม่?</b><div><button disabled={!attack} onClick={()=>attack&&update(state=>continueRepeatAttackAfterDodge(state,pending.attackerId,attack.id))}>{attack?'โจมตีซ้ำ':'ไม่มีไพ่โจมตี'}</button><button className="mock-muted-button" onClick={()=>update(state=>declineRepeatAttackAfterDodge(state,pending.attackerId))}>ไม่โจมตีซ้ำ</button></div></section>})()}
    {gameState.pendingDestroyMount&&(()=>{const pending=gameState.pendingDestroyMount,target=getPlayerById(gameState,pending.targetId);return target&&<section className="local-repeat-attack" role="dialog"><b>โจมตีสำเร็จ ต้องการทำลายพาหนะของเป้าหมายหรือไม่?</b><div>{target.equipment.offensiveMount&&<button onClick={()=>update(state=>destroyTargetMountAfterDamage(state,pending.attackerId,target.id,'offensiveMount'))}>ทำลาย {target.equipment.offensiveMount.name}</button>}{target.equipment.defensiveMount&&<button onClick={()=>update(state=>destroyTargetMountAfterDamage(state,pending.attackerId,target.id,'defensiveMount'))}>ทำลาย {target.equipment.defensiveMount.name}</button>}</div><button className="mock-muted-button" onClick={()=>update(state=>declineDestroyTargetMount(state,pending.attackerId))}>ไม่ทำลาย</button></section>})()}
    {gameState.pendingForceAttackDamage&&(()=>{const pending=gameState.pendingForceAttackDamage,attacker=getPlayerById(gameState,pending.attackerId);if(!attacker)return null;const choices=[...attacker.hand,...Object.values(attacker.equipment).filter((card):card is Card=>Boolean(card))];const toggle=(id:string)=>setForceDiscardRefs(current=>current.includes(id)?current.filter(ref=>ref!==id):current.length<2?[...current,id]:current);return <section className="local-repeat-attack" role="dialog"><b>เป้าหมายหลบสำเร็จ<br/>ต้องการทิ้งไพ่ 2 ใบเพื่อบังคับให้โจมตีโดนหรือไม่?</b><div className="local-force-cards">{choices.map(card=><button key={card.id} className={forceDiscardRefs.includes(card.id)?'selected-card':''} onClick={()=>toggle(card.id)}>{card.name}</button>)}</div><div><button disabled={forceDiscardRefs.length!==2} onClick={()=>update(state=>{forceAttackDamageByDiscardingTwo(state,pending.attackerId,forceDiscardRefs);setForceDiscardRefs([])})}>ยืนยัน ({forceDiscardRefs.length}/2)</button><button className="mock-muted-button" onClick={()=>update(state=>{declineForceAttackDamage(state,pending.attackerId);setForceDiscardRefs([])})}>ยกเลิก</button></div></section>})()}
  </main>;
}
